[package]
name = "explorer-exe"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoinsuite-chronik-client = { path = "../../bitcoinsuite/bitcoinsuite-chronik-client" }
bitcoinsuite-error =  { path = "../../bitcoinsuite/bitcoinsuite-error" }
explorer-server = { path = "../explorer-server" }
tokio = { version = "1.14", features = ["full"] }
futures = "0.3"
axum = "0.5.7"
